development:
  server:
    host: http://localhost
    port: "1323"
  db:
    username: "postgres"
    password: "postgres"
    database: "codeforces_problems"
production:
  server:
    host: http://togatoga.net
    port: "1323"
  db:
    username: "postgres"
    password: "postgres"
    database: "codeforces_problems"
